### ISSUE TITLE
Class Coloring

### ISSUE THREAD

**Issue by Resike** [Phanx/PhanxChat#2]
Would be nice to color the player names when they join/leave group.

"PlayerName-ServerName has joined/left the raid group."

**Comment by Phanx** [comment]
Those names aren't actually links, so they don't contain the information needed to color them. For "joined" messages it would be possible to scan the group, find the player who joined, and get their class that way. For "left" messages it's even more work, since I'd have to keep track of group members names, realms and classes on an ongoing basis to have access to it *after* someone left the group.

It's certainly *possible* do implement such a feature, but I probably won't add it to PhanxChat. It could easily be done with a standalone addon, that could be extended to detecting and coloring un-linked player names in various other messages as well.

**Comment by Resike** [comment]
I see, i might look into it and hack something together.
