### ISSUE TITLE
Request: EditBox backdrop and position

### ISSUE THREAD

**Issue by jeymerie** [Phanx/PhanxChat#30]
Hey,

First of all, thanks for the amazing work you're doing (i really enjoy all your addons).
Your chat is certainly the best chataddon i've seen so far, i mean lightweight and minimalist ...
But i have to add some custom code all the time in it only to add some background to the editbox (you could add it in nearly 2 lines and maybe add a slider in the  condif to set the opaticity (or the color)) and to move the editbox so it's aligned with my chat frame (but you can do nothing for that i guess ^^).

I have to re-add my modifictions each time i update, so, and as it could be a general feature many people could like, have no perf impact and can be deleted by only changing the alpha to 0, may you add it ?

Regards,

Clean

**Comment by Phanx** [comment]
I don't plan to add any new options for adding, removing, or recoloring textures to PhanxChat.

The existing "remove extra textures" option was originally added back in the Wrath of the Lich King expansion when Blizzard significantly changed the look of the chat tabs and edit box; the option just restores the original pre-patch appearance. Nowadays it might make more sense to call that option "use WoW classic appearance" since from the point of view of modern players, what's removed aren't *extra* textures anymore, but I'm probably not going to spend time renaming it.

If you're manually applying your changes after each update, I'd recommend automating that process. Do a **diff** between your version and the original version to create a patch file, and then after each update, you can just **apply** your patch file and it will add/remove/change all the affected lines. Personally I have a whole collection of patch files that I apply whenever I update addons, using a single shell script (the Windows equivalent is a batch file).
