### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Darcspirit** [Phanx/PhanxChat#4]
is there any chance you can add profiles to addon, would greatly help in setting up dozens of toons?

**Comment by Phanx** [comment]
I'm not sure how profiles would help with multiple toons; PhanxChat's settings are already account-wide, so all characters on your account use the same settings. If you're multiboxing or sharing your UI with friends, profiles still won't help, since addon settings are saved per-account; you'd still need to copy the actual saved variables file over into the correct account folder(s).

If you really need profiles (eg. you want different characters on your account to have different settings for some reason) you can use Reflux to emulate them.

At this time I have no plans to add any profile features in PhanxChat.
